name: Build Branch81_tmp

on:
  schedule:
    - cron: '*/3 * * * *'  # Poll SCM equivalent: every 3 minutes
  push:
    branches:
      - Branch81_tmp
  workflow_dispatch:  # Manual trigger

jobs:
  build:
    runs-on: ubuntu-latest  # Replace with 'self-hosted' if restricted to a specific label like 'master'

    env:
      JAVA_HOME: /opt/jdk1.8.0_171
      JOB_NAME: Branch81_tmp
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          repository: nook_cloud_eng/bncloud
          ref: Branch81_tmp
          fetch-depth: 0

      - name: Set up JDK 1.8.0_171
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'  # Or 'adopt' if you have a custom JDK
          java-version: '8.0.171'

      - name: Set Maven Version 3.2.2
        uses: s4u/setup-maven-action@v1
        with:
          maven-version: '3.2.2'

      - name: Build with Maven
        run: |
          mvn -e -Pjenkins -Djunit \
              -Dbuild.id=${{ env.JOB_NAME }}-${{ github.run_number }} \
              -Dscm.rev=$(git rev-parse HEAD) \
              -Dscm.branch=refs/heads/Branch81_tmp \
              -Dbuild.date=$(date +%Y%m%d%H%M%S) \
              clean deploy -DskipTests

      - name: Archive Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: maven-artifacts
          path: '**/target/*.jar'  # Adjust as needed
